### PR TITLE
upgrade links to https

### PR DESCRIPTION
**Pull request by vszakats**

### CODE REVIEW

**Comment by vague666** [comment]
A blanket update is not a good idea. For irssi.org links it's ok but all other websites have to be verified that they work over https

**Comment by vszakats** [comment]
These are all verified ones.

**Comment by vszakats** [comment]
Here's the output of my checker tool. All of these were clear cut cases, either with identical content, ETag, HTTPS-Everywhere match, HSTS header indication, and one 'known good' which is any of the former, or a previously manually verified one case.
```
filename,line,status,details,original-url,"new-url"
./LICENSE,1,OK,,http://creativecommons.org/licenses/by-sa/3.0/,"https://creativecommons.org/licenses/by-sa/3.0/"
./_articles/2015-02-12-hacking-irssi.org.markdown,5,OK,HSTS-SUB,http://kuttler.eu,"https://kuttler.eu/"
./_articles/2015-02-12-hacking-irssi.org.markdown,11,OK,HTTPS-EV,http://irssi.org,"https://irssi.org/"
./_articles/2015-02-12-hacking-irssi.org.markdown,31,OK,HTTPS-EV,http://username.github.io/irssi.github.io/,"https://username.github.io/irssi.github.io/"
./_articles/2015-02-12-adding-articles-to-irssi.org.markdown,5,OK,HSTS-SUB,http://kuttler.eu,"https://kuttler.eu/"
./_articles/2015-02-12-adding-articles-to-irssi.org.markdown,11,OK,HTTPS-EV,http://irssi.org,"https://irssi.org/"
./_articles/2015-02-12-adding-articles-to-irssi.org.markdown,17,OK,HTTPS-EV,http://jekyllrb.com,"https://jekyllrb.com/"
./_articles/2015-02-12-adding-articles-to-irssi.org.markdown,25,OK,HTTPS-EV,http://vuejs.org/examples/,"https://vuejs.org/examples/"
./_data/security.yml,5,OK,HTTPS-EV,http://www.openwall.com/xxx,"https://www.openwall.com/xxx"
./_includes/navbar.html,8,OK,HTTPS-EV,http://scripts.irssi.org/,"https://scripts.irssi.org/"
./_includes/sec_txt/master.txt,81,OK,HTTPS-EV,http://cve.mitre.org/cgi-bin/cvename.cgi?name=,"https://cve.mitre.org/cgi-bin/cvename.cgi?name="
./_includes/paginate.html,3,OK,HSTS-SUB,http://getbootstrap.com/components/,"https://getbootstrap.com/components/"
./_includes/paginate.html,19,OK,HTTPS-EV,http://jekyllrb.com/docs/pagination/,"https://jekyllrb.com/docs/pagination/"
./_includes/footer.html,30,OK,,http://creativecommons.org/licenses/by-sa/3.0/,"https://creativecommons.org/licenses/by-sa/3.0/"
./_posts/2016-01-18-irssi-0.8.18-beta-released.markdown,27,OK,,http://download.opensuse.org/repositories/home:/ailin_nemui:/irssi-test/,"https://download.opensuse.org/repositories/home:/ailin_nemui:/irssi-test/"
./_posts/2016-01-18-irssi-0.8.18-beta-released.markdown,35,OK,HTTPS-EV,http://www.linkedin.com/groups?gid=147751,"https://www.linkedin.com/groups?gid=147751"
./_posts/2015-12-21-irssi-0.8.18-beta-released.markdown,28,OK,,http://download.opensuse.org/repositories/home:/ailin_nemui:/irssi-test/,"https://download.opensuse.org/repositories/home:/ailin_nemui:/irssi-test/"
./_posts/2015-12-21-irssi-0.8.18-beta-released.markdown,36,OK,HTTPS-EV,http://www.linkedin.com/groups?gid=147751,"https://www.linkedin.com/groups?gid=147751"
./_posts/2010-04-03-irssi-0.8.15-released.markdown,19,OK,HSTS-SUB,http://www.facebook.com/irssi,"https://www.facebook.com/irssi"
./_posts/2010-04-03-irssi-0.8.15-released.markdown,20,OK,HTTPS-EV,http://www.linkedin.com/groups?gid=147751,"https://www.linkedin.com/groups?gid=147751"
./_posts/2007-10-06-irssi-0.8.12-released.markdown,12,OK,HTTPS-EV,http://irssi.org/files/irssi-0.8.12.tar.gz,"https://irssi.org/files/irssi-0.8.12.tar.gz"
./_posts/2007-10-06-irssi-0.8.12-released.markdown,12,OK,HTTPS-EV,http://irssi.org/files/irssi-0.8.12.tar.gz,"https://irssi.org/files/irssi-0.8.12.tar.gz"
./_posts/2016-09-21-irssi-0.8.20-released.markdown,29,OK,HTTPS-EV,http://www.ubuntu.com/usn/usn-3086-1/,"https://www.ubuntu.com/usn/usn-3086-1/"
./_posts/2006-02-02-irssi-0.8.10a-released.markdown,7,OK,HTTPS-EV,http://www.gentoo.org/,"https://www.gentoo.org/"
./_posts/2006-02-02-irssi-0.8.10a-released.markdown,8,OK,HTTPS-EV,http://www.debian.org/,"https://www.debian.org/"
./_posts/2006-02-02-irssi-0.8.10a-released.markdown,14,OK,HTTPS-EV,http://www.irssi.org/download,"https://www.irssi.org/download"
./_posts/2009-04-01-irssi-0.8.13-released.markdown,22,OK,HTTPS-EV,http://www.exherbo.org/,"https://www.exherbo.org/"
./_posts/2009-04-01-irssi-0.8.13-released.markdown,42,OK,HTTPS-EV,http://www.linkedin.com/groups?gid=147751,"https://www.linkedin.com/groups?gid=147751"
./_posts/2009-04-01-irssi-0.8.13-released.markdown,43,OK,HSTS-SUB,http://www.facebook.com/pages/IRSSI/40806744458?ref=mf,"https://www.facebook.com/pages/IRSSI/40806744458?ref=mf"
./_posts/2014-06-10-the-future-of-irssi.markdown,95,OK,HTTPS-EV,http://scripts.irssi.org/,"https://scripts.irssi.org/"
./_posts/2014-06-10-the-future-of-irssi.markdown,99,OK,HTTPS-EV,http://scripts.irssi.org/,"https://scripts.irssi.org/"
./_posts/2014-06-10-the-future-of-irssi.markdown,104,OK,HTTPS-EV,http://scripts.irssi.org/,"https://scripts.irssi.org/"
./_posts/2014-10-11-irssi-0.8.17-released.markdown,19,OK,HTTPS-EV,http://www.linkedin.com/groups?gid=147751,"https://www.linkedin.com/groups?gid=147751"
./_posts/2014-05-29-irssi-0.8.16-released.markdown,20,OK,HSTS-SUB,http://www.facebook.com/irssi,"https://www.facebook.com/irssi"
./_posts/2014-05-29-irssi-0.8.16-released.markdown,22,OK,HTTPS-EV,http://www.linkedin.com/groups?gid=147751,"https://www.linkedin.com/groups?gid=147751"
./_posts/2013-09-15-irssi-0.8.16-rc1-released.markdown,17,OK,HSTS-SUB,http://www.facebook.com/irssi,"https://www.facebook.com/irssi"
./_posts/2013-09-15-irssi-0.8.16-rc1-released.markdown,19,OK,HTTPS-EV,http://www.linkedin.com/groups?gid=147751,"https://www.linkedin.com/groups?gid=147751"
./_posts/historical/2006-05-02-apply-for-the-summer-of-code.markdown,7,OK,HSTS-SUB,http://code.google.com/soc,"https://code.google.com/soc"
./_posts/historical/1999-09-13-nt.markdown,8,OK,HTTPS-EV,http://www.iki.fi/jetro/,"https://www.iki.fi/jetro/"
./_posts/historical/2006-04-20-irssi-and-the-summer-of-code.markdown,102,OK,HTTPS-EV,http://www.freebsd.org/projects/summerofcode.html,"https://www.freebsd.org/projects/summerofcode.html"
./_posts/historical/2001-07-26-nightly-.deb-cvs-snapshots.markdown,10,OK,HTTPS-EV,http://irssi.org/debian/,"https://irssi.org/debian/"
./_posts/historical/2001-07-26-nightly-.deb-cvs-snapshots.markdown,11,OK,HTTPS-EV,http://irssi.org/debian/,"https://irssi.org/debian/"
./_posts/historical/2001-08-12-nightly-.deb-cvs-snapshot-changes.markdown,12,OK,HTTPS-EV,http://irssi.org/debian,"https://irssi.org/debian"
./_posts/historical/2001-08-12-nightly-.deb-cvs-snapshot-changes.markdown,13,OK,HTTPS-EV,http://irssi.org/debian/,"https://irssi.org/debian/"
./_posts/2010-12-26-irssi-0.8.15-on-windows-testing-help-needed.markdown,14,OK,HTTPS-EV,http://irssi.org/files/irssi_0_8_15_windows_testing.txt,"https://irssi.org/files/irssi_0_8_15_windows_testing.txt"
./_posts/2010-12-26-irssi-0.8.15-on-windows-testing-help-needed.markdown,16,OK,HTTPS-EV,http://www.irssi.org/files/irssi_0_8_15_TEST3.exe,"https://www.irssi.org/files/irssi_0_8_15_TEST3.exe"
./_posts/2016-03-24-irssi-0.8.19-released.markdown,18,OK,,http://download.opensuse.org/repositories/home:/ailin_nemui:/irssi-test/,"https://download.opensuse.org/repositories/home:/ailin_nemui:/irssi-test/"
./_posts/2016-03-24-irssi-0.8.19-released.markdown,23,OK,,http://download.opensuse.org/repositories/home:/ailin_nemui:/irssi-git/,"https://download.opensuse.org/repositories/home:/ailin_nemui:/irssi-git/"
./_posts/2016-03-24-irssi-0.8.19-released.markdown,32,OK,HTTPS-EV,http://www.linkedin.com/groups?gid=147751,"https://www.linkedin.com/groups?gid=147751"
./_posts/2007-04-25-irssi-0.8.11-released.markdown,12,OK,HTTPS-EV,http://irssi.org/files/irssi-0.8.11.tar.gz,"https://irssi.org/files/irssi-0.8.11.tar.gz"
./_posts/2007-04-25-irssi-0.8.11-released.markdown,12,OK,HTTPS-EV,http://irssi.org/files/irssi-0.8.11.tar.gz,"https://irssi.org/files/irssi-0.8.11.tar.gz"
./_posts/2014-11-11-the-gnome-foundation-needs-your-help.markdown,8,OK,HTTPS-EV,http://www.gnome.org,"https://www.gnome.org/"
./_posts/2014-11-11-the-gnome-foundation-needs-your-help.markdown,9,OK,HTTPS-EV,http://www.gnome.org/groupon,"https://www.gnome.org/groupon"
./_posts/2014-11-11-the-gnome-foundation-needs-your-help.markdown,22,OK,HTTPS-EV,http://www.linkedin.com/groups?gid=147751,"https://www.linkedin.com/groups?gid=147751"
./_posts/2016-02-29-irssi-0.8.18-released.markdown,24,OK,HTTPS-EV,http://www.linkedin.com/groups?gid=147751,"https://www.linkedin.com/groups?gid=147751"
./_posts/2010-10-07-introducing-stalker-nickname-history-for-irssi.markdown,20,OK,HSTS-SUB,http://github.com/symkat/Stalker,"https://github.com/symkat/Stalker"
./_posts/2010-10-07-introducing-stalker-nickname-history-for-irssi.markdown,20,OK,HSTS-SUB,http://github.com/symkat/Stalker,"https://github.com/symkat/Stalker"
./_posts/2007-02-20-irssi-0.8.11-rc1-released.markdown,12,OK,HTTPS-EV,http://irssi.org/files/irssi-0.8.11-rc1.tar.gz,"https://irssi.org/files/irssi-0.8.11-rc1.tar.gz"
./_posts/2007-02-20-irssi-0.8.11-rc1-released.markdown,12,OK,HTTPS-EV,http://irssi.org/files/irssi-0.8.11-rc1.tar.gz,"https://irssi.org/files/irssi-0.8.11-rc1.tar.gz"
./_posts/2007-09-26-irssi-0.8.12-rc1-released.markdown,13,OK,HTTPS-EV,http://irssi.org/files/irssi-0.8.12-rc1.tar.gz,"https://irssi.org/files/irssi-0.8.12-rc1.tar.gz"
./_posts/2007-09-26-irssi-0.8.12-rc1-released.markdown,13,OK,HTTPS-EV,http://irssi.org/files/irssi-0.8.12-rc1.tar.gz,"https://irssi.org/files/irssi-0.8.12-rc1.tar.gz"
./_posts/2008-01-30-windows-installer.markdown,8,OK,,http://joshdick.net/,"https://joshdick.net/"
./_posts/2008-01-30-windows-installer.markdown,9,OK,HTTPS-EV,http://www.hartwork.org/,"https://www.hartwork.org/"
./_posts/2008-01-30-windows-installer.markdown,30,OK,HTTPS-EV,http://www.irssi.org/files/irssi_0_8_12_setup_2.exe,"https://www.irssi.org/files/irssi_0_8_12_setup_2.exe"
./_posts/2008-01-30-windows-installer.markdown,31,OK,HTTPS-EV,http://www.irssi.org/files/irssi_0_8_12_usb_2.zip,"https://www.irssi.org/files/irssi_0_8_12_usb_2.zip"
./_posts/2015-12-14-irssi-website-now-on-github-pages.markdown,9,OK,,http://dequis.org/,"https://dequis.org/"
./_posts/2015-12-14-irssi-website-now-on-github-pages.markdown,15,OK,HTTPS-EV,http://www.linkedin.com/groups?gid=147751,"https://www.linkedin.com/groups?gid=147751"
./_posts/2017-10-22-irssi-1.0.5-released.markdown,14,OK,,http://freenode.live,"https://freenode.live/"
./_posts/2017-05-12-fuzzing-irssi.markdown,218,OK,,http://softdroid.net/,"https://softdroid.net/"
./_posts/2017-05-12-fuzzing-irssi.markdown,219,OK,,http://softdroid.net/fuzzing-irssi-ru,"https://softdroid.net/fuzzing-irssi-ru"
./_security/_template.txt,6,OK,HTTPS-EV,http://www.openwall.com/xxx,"https://www.openwall.com/xxx"
./_security_html/_template.txt,6,OK,HTTPS-EV,http://www.openwall.com/xxx,"https://www.openwall.com/xxx"
./_tools/Release.md,33,OK,HTTPS-EV,http://irssi.org/NEWS,"https://irssi.org/NEWS"
./assets/js/anchor.js,236,OK,HTTPS-EV,http://stackoverflow.com/a/5898748/1154642,"https://stackoverflow.com/a/5898748/1154642"
./assets/js/irssi.js,1,OK,HTTPS-EV,http://stackoverflow.com/a/34003331,"https://stackoverflow.com/a/34003331"
./development.markdown,45,OK,HTTPS-EV,http://scripts.irssi.org/,"https://scripts.irssi.org/"
./documentation/tips.markdown,84,OK,HTTPS-EV,http://scripts.irssi.org/,"https://scripts.irssi.org/"
./documentation/tips.markdown,86,OK,HTTPS-EV,http://irssi.org/scripts/,"https://irssi.org/scripts/"
./documentation/tips.markdown,94,OK,HTTPS-EV,http://irssi.org/scripts/,"https://irssi.org/scripts/"
./documentation/tips.markdown,203,OK,HTTPS-EV,http://sourceforge.net/p/zsh/code/ci/master/tree/Completion/Unix/Command/_irssi?format=raw,"https://sourceforge.net/p/zsh/code/ci/master/tree/Completion/Unix/Command/_irssi?format=raw"
./documentation/tips.markdown,204,OK,HTTPS-EV,http://scripts.irssi.org/scripts/hide.pl,"https://scripts.irssi.org/scripts/hide.pl"
./documentation/tips.markdown,207,OK,HTTPS-EV,http://scripts.irssi.org/scripts/news.pl,"https://scripts.irssi.org/scripts/news.pl"
./documentation/faq.markdown,60,OK,HTTPS-EV,http://tmux.github.io/,"https://tmux.github.io/"
./documentation/faq.markdown,60,OK,HTTPS-EV,http://www.gnu.org/software/screen/screen.html,"https://www.gnu.org/software/screen/screen.html"
./documentation/faq.markdown,76,OK,HTTPS-EV,http://dgl.cx/irssi/hack-whois-in-current-window.pl,"https://dgl.cx/irssi/hack-whois-in-current-window.pl"
./documentation/settings.markdown,6,OK,,http://creativecommons.org/licenses/by-sa/2.5/,"https://creativecommons.org/licenses/by-sa/2.5/"
./documentation/settings.markdown,983,OK,HTTPS-EV,http://irssi.org/documentation/special_vars,"https://irssi.org/documentation/special_vars"
./documentation/settings.markdown,1504,OK,HTTPS-EV,http://irssi.org/documentation/special_vars,"https://irssi.org/documentation/special_vars"
./documentation/settings.markdown,1677,OK,HTTPS-EV,http://irssi.org/documentation/formats,"https://irssi.org/documentation/formats"
./documentation/settings.markdown,1725,OK,,http://creativecommons.org/licenses/by-sa/2.5/,"https://creativecommons.org/licenses/by-sa/2.5/"
./documentation/startup.markdown,6,OK,HTTPS-EV,http://www.gnu.org/licenses/fdl.html,"https://www.gnu.org/licenses/fdl.html"
./documentation/startup.markdown,139,OK,HTTPS-EV,http://quadpoint.org/articles/irssisplit/,"https://quadpoint.org/articles/irssisplit/"
./documentation/startup.markdown,721,OK,HTTPS-EV,http://www.gnu.org/licenses/fdl.html,"https://www.gnu.org/licenses/fdl.html"
./documentation/startup.markdown,722,OK,KNOWN-GOOD,http://www.chiark.greenend.org.uk/~sgtatham/putty/,"https://www.chiark.greenend.org.uk/~sgtatham/putty/"
./download.markdown,58,OK,HTTPS-EV,http://backports.debian.org/,"https://backports.debian.org/"
./download.markdown,76,OK,HTTPS-EV,http://brew.sh/,"https://brew.sh/"
./download.markdown,96,OK,HTTPS-EV,http://software.opensuse.org/package/irssi,"https://software.opensuse.org/package/irssi"
./download.markdown,161,OK,HTTPS-EV,http://build.opensuse.org/,"https://build.opensuse.org/"
./modules.markdown,13,OK,,http://cybione.org/~irssi-xmpp/,"https://cybione.org/~irssi-xmpp/"
./modules.markdown,14,OK,,http://psyc.eu/,"https://psyc.eu/"
./modules.markdown,15,OK,HTTPS-EV,http://quassel-irc.org/,"https://quassel-irc.org/"
./modules.markdown,16,OK,HTTPS-EV,http://robustirc.net/,"https://robustirc.net/"
./support/irc.markdown,10,OK,HTTPS-EV,http://freenode.net/,"https://freenode.net/"
```

**Comment by vague666** [comment]
I went through all dubious ones manually and I agree they all work :) and the dtach link is correct too but visiting it redirects to https://sourceforge.net/projects/dtach/ so maybe the link can be updated

**Review by vague666 — APPROVED** [review]

**Comment by vszakats** [comment]
Great, thank you for double-checking! Committed the `dtach` update.

**Comment by vszakats** [comment]
This sadly didn't fix the issue I was aiming at. When clicking on a documentation link, it still ends up on an insecure URL. E.g. when clicking on 'Settings' on the 'Help' page, the URL is <https://irssi.org/documentation/settings>, which then gets redirected by the server to <http://irssi.org/documentation/settings/> (note the HTTP). This is possibly so because the  'Enforce HTTPS' option isn't enabled on the GitHub Settings page for this project, and/or because it is served as HTTP over to Cloudflare, which then adds HTTPS.

GitHub does support HTTPS for custom domains, so the most ideal solution would be to use that and remove Cloudflare from the setup.

A workaround is to add a slash suffix for all links where required to avoid the redirect kickiing-in. I can do that in another PR, though removing Cloudflare (and making the full connection, from GitHub to client, HTTPS) would be a nice touch either way.

**Pull request merged**
