### PR TITLE
Update settings page for 1.0.0 and current git

### PR DESCRIPTION
**Pull request by dequis**
Not entirely sure about the behavior of rejoin_channels_on_reconnect

### CODE REVIEW

**Comment by dequis** [comment]
@vague666 rejoin_channels_on_reconnect is yours (mostly), did i get the description right?

**Comment by vague666** [comment]
Yes, looks good

**Comment by ailin-nemui** [comment]
Thanks for the update, is it possible that an image you linked is missing?

**Comment by dequis** [comment]
Yeah, forgot to 'git add' it first, and then apparently forgot to 'git push' it...

**Pull request merged**
