### PR TITLE
Clean shell scripts

### PR DESCRIPTION
**Pull request by zapashcanon**
Hi,

I just fixed a few things spotted by shellcheck.

Cheers.

### CODE REVIEW

**Comment by ailin-nemui** [comment]
you have enabled `-e` (which is generally considered good practice) but made no effort to verify all the return codes in the script. thus it may now stop working at places that were silently ignored (soft failures) before

**Comment by zapashcanon** [comment]
In `update_release.sh`, `set -e` was already in the shebang. I just moved it to make it explicit in case someone wants to run the script another way ; e.g. `bash update_relase.sh` instead of `./update_release.sh`.

In `upload_release.sh`, I don't see any place where the script relies on an exit code different from zero.

**Comment by ailin-nemui** [comment]
for example, `github-release delete`

**Comment by ailin-nemui** [comment]
closing for inactivity

**Pull request closed without merging**
