### PR TITLE
Update keyserver to use roundrobin host

### PR DESCRIPTION
**Pull request by vague666**

### CODE REVIEW

**Comment by ailin-nemui** [comment]
gpg: keyserver receive failed: No data

doesn't work ;(

**Comment by ailin-nemui** [comment]
@vague666 but is that in any way /better/ than wwwkeys?

**Comment by vague666** [comment]
Does wwwkeys work for you? I can't connect to it

**Comment by vague666** [comment]
If it works then it's ok to close this PR

**Comment by ailin-nemui** [comment]
odd, has always worked for me

**Comment by vague666** [comment]
I tried now to connect to wwwkeys from work and from home, neither can connect
vague@IS-C0HVFBY:~$ time gpg --keyserver wwwkeys.pgp.net --recv-keys '7EE6 5E30 82A5 FB06 AC7C 368D 00CC B587 DDBE F0E1'                                                                                                                                                                                                       
^C                                                                                                                                                                                                                                                                                                                            
gpg: signal Interrupt caught ... exiting                                                                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                                                                                              
real    1m51,165s
user    0m0,007s
sys     0m0,003s

**Comment by ailin-nemui** [comment]
lets do this then, mit is also good

**Pull request merged**
