### PR TITLE
Add FreeBSD to the install page

### PR DESCRIPTION
**Pull request by LemonBoy**

### CODE REVIEW

**Comment by ailin-nemui** [comment]
did you test it?

**Comment by LemonBoy** [comment]
A user in `#irssi` confirmed that the command is right if that's what you're asking.

**Comment by ailin-nemui** [comment]
I mean if the website looks right

**Comment by dequis** [comment]
lol doesn't even build

```
Liquid Exception: Invalid syntax for include tag: name="slackware" text="**Slackware**" include dl_os_icon.html name="freebsd" text="**FreeBSD**" Valid syntax: {% include file.ext param='value' param2='value' %} in download/index.markdown
jekyll 3.3.1 | Error:  Invalid syntax for include tag:

  name="slackware" text="**Slackware**"
include dl_os_icon.html name="freebsd" text="**FreeBSD**"
```

```
<div class="dlc row">{%
include dl_os_icon.html name="Windows" text="**Windows**" %}{%
include dl_os_icon.html name="debian" text="**Debian**" %}{%
include dl_os_icon.html name="ubuntu" text="**Ubuntu**" %}{%
include dl_os_icon.html name="macosx" text="**OS X**" %}{%
include dl_os_icon.html name="gentoo" text="**Gentoo**" %}{%
include dl_os_icon.html name="openSUSE" text="**SUSE**" %}{%
include dl_os_icon.html name="arch" text="**ArchLinux**" %}{%
include dl_os_icon.html name="fedora" text="**Fedora/RHEL**" %}{%
include dl_os_icon.html name="opencsw" text="**Solaris**" %}{%
include dl_os_icon.html name="slackware" text="**Slackware**"
include dl_os_icon.html name="freebsd" text="**FreeBSD**"
%}
```

**Comment by dequis** [comment]
Added fix commit

screenshot

**Pull request merged**
