### PR TITLE
remove leading spaces (fixes a part of #39)

### PR DESCRIPTION
**Pull request by Gryllida**
(some people paste them into irssi by mistake and don't always notice)

### CODE REVIEW

**Comment by dequis** [comment]
Oh. That explains the overwhelming amount of failures.

...but some people copypaste the examplenet lines sometimes

Why "a part of"? What is missing from this?

**Comment by Gryllida** [comment]
Re "a part of" - perhaps there are other files which have the same problem, I did not check. I only corrected the one which was mentioned on IRC today.

**Comment by dequis** [comment]
Good enough then

**Comment by dequis** [comment]
Thanks!

**Pull request merged**
